### ISSUE TITLE
is chunked request bodies supported?

### ISSUE THREAD

**Issue by willdonggg** [openresty/lua-resty-upload#32]
I'm developing a file server with openresty, the client is a java program which upload the file with stream so that not too much memory used , but I get the error "_chunked request bodies not supported yet_", so I want to know does lua_resty_upload support chunked request bodies? if not, is there any suggest to handle this, thanks.

**Comment by agentzh** [comment]
@willdonggg I think the error message you're getting is quite self-explanatory :)

**Comment by willdonggg** [comment]
@agentzh thanks, as the message says, lua_resty_upload does not support Chunked Transfer. would you like to give some suggestion that how to handle chunked request body with openresty or nginx

**Comment by agentzh** [comment]
@willdonggg Well, you can use `ngx.req.read_body` and `ngx.re.get_body_data` instead which uses nginx's built-in request body reader with chunked encoding support. But the current nginx built-in request body reader API lacks streaming processing support like the `ngx.req.socket` Lua API used by this `lua-resty-upload` library.

The ultimate solution is to add chunked encoding support to the `ngx.req.socket(false)` API (excluding those raw downstream cosockets) so that this Lua library can work out of the box without any Lua code changes. Patches welcome :)

**Comment by willdonggg** [comment]
@agentzh thanks for your answer

**Comment by wyxloading** [comment]
hi @agentzh , sorry to bother. Does this issue has any progress?

After checking `ngx.req.read_body` and `ngx.req.get_body_data`, i found that this solution may cause performance issue (since read_body may read the whole request body synchronously, even more if the request body larger than `client_body_buffer_size`, it will write to file instead, which cost more disk io).

Since the `ngx.req.socket` method support streaming processing, i think it is definitely cost less memory and disk io.

Any suggestions to solve this problem ?

thanks

**Comment by Triple-Z** [comment]
I have the same question as @wyxloading . In the documentation it says:

> "Instead of writing the data chunk into files (as shown in the example above), you can also write the data chunks to upstream cosocket connections if you do not want to save the data on local file systems."

Can anyone do a little showcase here to show us how to "write the data chunks to upstream cosocket connections"?
